In [1]:
import numpy as np

### The Basics

### Create Array

In [2]:
a = np.array([1,2,3], dtype='int16')
print(a)

[1 2 3]


In [3]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b) 

[[9. 8. 7.]
 [6. 5. 4.]]


In [4]:
# Get Dimension
print(a.ndim)
print(b.ndim)

1
2


In [5]:
# Get Shape
print(a.shape)
print(b.shape)

(3,)
(2, 3)


In [6]:
# Get Type
print(a.dtype)
print(b.dtype)

int16
float64


In [7]:
# Get Size
print(a.itemsize)
print(b.itemsize)

2
8


### Accessing/Changing specific elements, rows, columns, etc

In [8]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [9]:
# Get a specific element [row, column]
print(a[0, 3])
print(a[1,-2])

4
13


In [10]:
# Get a specific row
print(a[0, :])

[1 2 3 4 5 6 7]


In [11]:
# Get a specific column
print(a[:, 2])

[ 3 10]


In [12]:
# Getting a little more fancy [startindex:endindex:stepsize]
print(a[0, 1:6:2])

[2 4 6]


In [14]:
# Changing a specific element
a[1,5] = 20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [15]:
# Changing a specific row
a[0,:] = [2,3,2,3,2,3,2]
print(a)

[[ 2  3  2  3  2  3  2]
 [ 8  9 10 11 12 20 14]]


### Initializing Different Types of Arrays

In [16]:
# All 0s matrix
print(np.zeros(3))
print('\n')
print(np.zeros((2,3)))

[0. 0. 0.]


[[0. 0. 0.]
 [0. 0. 0.]]


In [17]:
# All 1s matrix
print(np.ones(3))
print('\n')
print(np.ones((2,3)))

[1. 1. 1.]


[[1. 1. 1.]
 [1. 1. 1.]]


In [18]:
# Any other number 
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [19]:
np.full(a.shape, 10)

array([[10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10]])

In [20]:
# Random decimal numbers
np.random.rand(4,2)

array([[0.36662741, 0.94947546],
       [0.76838685, 0.76459655],
       [0.11946461, 0.64661228],
       [0.88836357, 0.40083945]])

In [21]:
# Random integer numbers
np.random.randint(-3, 7, size=(3,1))

array([[-3],
       [-3],
       [-3]])

In [22]:
# The identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [23]:
# Repeat an array
arr = np.array([[1,2,3]])
r = np.repeat(arr, 3, axis=0)
print(r)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


#### Task 1: Create Below Matrix
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]

In [24]:
output = np.ones((5,5))
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [25]:
z = np.zeros((3,3))
z[1,1] = 9
print(z)

[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]


In [26]:
output[1:-1, 1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### Be careful when copying arrays!!!

In [27]:
a = np.array([1,2,3])
b = a
b

array([1, 2, 3])

In [28]:
b[0] = 100
b

array([100,   2,   3])

In [29]:
# point to same thing
a

array([100,   2,   3])

In [30]:
a = np.array([1,2,3])
b = a.copy()
b

array([1, 2, 3])

In [31]:
b[0] = 100
a

array([1, 2, 3])

### Mathematics

In [32]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [33]:
a + 2

array([3, 4, 5, 6])

In [34]:
a - 2

array([-1,  0,  1,  2])

In [35]:
a * 3

array([ 3,  6,  9, 12])

In [36]:
a / 3

array([0.33333333, 0.66666667, 1.        , 1.33333333])

In [37]:
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [38]:
a ** 2

array([ 1,  4,  9, 16])

### Linear Algebra

In [39]:
a = np.ones((2,3))
b = np.full((3,2), 2)

In [40]:
np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

In [41]:
# Find the determinant

c = np.identity(4)
np.linalg.det(c)

1.0

### Statistics

In [42]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [43]:
np.min(stats)

1

In [44]:
np.max(stats)

6

In [45]:
# Max each row axis = 1
np.max(stats, axis=1)

array([3, 6])

In [46]:
np.sum(stats)

21

In [47]:
# Sum each column axis = 0
np.sum(stats, axis=0)

array([5, 7, 9])

### Reorganizing Arrays

In [48]:
a = np.array([[1,2,3,4],[5,6,7,8]])
b = a.reshape(8,1)
b

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [49]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8]])

In [50]:
# Horizontal stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.hstack([v1,v2,v2])

array([1, 2, 3, 4, 5, 6, 7, 8, 5, 6, 7, 8])

### Load Data From File

In [51]:
filedata = np.genfromtxt('data.txt', delimiter=',')
filedata = filedata.astype('int32')
print(filedata)

[[  1  13  21  11 196  75   4   3  34   5   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  70   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  13  21  11 196  75   4   3  34   5   7   8   0   1   2   3   4   5]]


### Boolean Masking

In [52]:
filedata > 50

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False]])

In [53]:
np.any(filedata > 50, axis=0)

array([False, False, False, False,  True,  True, False,  True, False,
       False, False, False, False, False, False, False, False, False])

In [54]:
np.all(filedata > 50, axis=0)

array([False, False, False, False,  True,  True, False, False, False,
       False, False, False, False, False, False, False, False, False])

In [55]:
filedata[filedata > 50]

array([196,  75, 766,  70,  55, 196,  75])

### Advanced Indexing

In [56]:
a = np.array([1,2,3,4,5,6,7,8,9])
a[[0,1,8]]

array([1, 2, 9])

In [57]:
a = np.array([[1,2,3,4,5,6,7,8,9], [10,20,30,40,50,60,70,80,90]])
a[[0,1], [1,4]]

array([ 2, 50])

In [58]:
a[[0,1], 3:]

array([[ 4,  5,  6,  7,  8,  9],
       [40, 50, 60, 70, 80, 90]])